### ISSUE TITLE
Explain why underscores in filename?

### ISSUE THREAD

**Issue by wshayes** [belbio/bel_lang#48]
Why change 2.0.0 in filename to 2_0_0? 

SPECIFIED_VERSION_UNDERLINED = 2_0_0 

used for bel_v2_0_0.yaml, ebnf and parser file

**Comment by davidchen** [comment]
Relevant snippet:

```
parser_dir = '{}.versions.parser_v{}'.format(cur_dir_name, self.version_dots_as_underscores)
imported_parser_file = importlib.import_module(parser_dir)
```

`versions` is a directory name. The call to `importlib.import_module(...)` requires the directory of the file to be in the form of a Python import, i.e. the periods represent sub-directories. We need to have filenames in underscores rather than periods for these main reasons:

- Importing the parser file, YAML, etc. will require importing from sub-directories. Current usage of `importlib` requires periods to denote sub-directories so we can't have that in filename.
- [A period in filenames is often used as the standard separator between filename and extensions.](https://unix.stackexchange.com/a/274029)
- Although not themselves Python files, I'd like to keep a consistent file naming format since they are helper files in a Python project, thus using periods over underscores is highly discouraged.

The version with periods is for user usability and with underscores is for machine usability.
